# -*- coding: utf-8 -*-
"""LGMVIP- DataScience-02INTERMEDIATE LEVEL TASK-Task-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S3OCv6-bKKAl_jcpTffisSxoRufkDgxD
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/iris.csv")

data

data.info()

data.describe()

data.isnull()

data.isnull().sum()

data.head(10)

data.columns

data.rename(columns={'id':'id','SepalLengthCm':'sepal_length','SepalWidthCm':'sepal_width','PetalLengthCm':'petal_length','PetalWidthCm':'petal_width' , 'Species':'Species'},inplace=True)

plt.scatter(data['Species'], data['petal_length'])
plt.title("iris")
plt.xlabel('Species')
plt.ylabel('petal_length')
plt.show()

print(data["Species"].unique())

data['Species'].value_counts()

plt.figure(figsize=(12, 6))
sns.histplot(data.sepal_length)
plt.xlabel('no')
plt.ylabel('Sepal Length')
plt.title('Histogram of Sepal Length (Cm)', size=16)

correlation = data.corr()
correlation

sns.heatmap(data.corr(),annot=True,cmap='inferno')

sns.pairplot(data)

from wordcloud import WordCloud

text = " ".join(data.Species)

# Creating word_cloud with text as argument in .generate() method

word_cloud = WordCloud(collocations = False, background_color = 'white').generate(text)

# Display the generated Word Cloud

plt.imshow(word_cloud, interpolation='bilinear')

plt.axis("off")

plt.show()

X = data.iloc[:, :-1]
y = data.iloc[:, -1]
#X = data.drop('species', axis=1)
#y = data['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

fig = plt.figure(figsize=(10, 8))
_ = tree.plot_tree(clf, feature_names=X.columns, class_names=y.unique(), filled=True)